# Generated by Django 4.1.7 on 2023-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_customer_bluebook_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/LicensePic/'),
        ),
    ]
